# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=25)),
                ('sex', models.CharField(default='male', max_length=20)),
                ('pswd', models.CharField(max_length=100)),
            ],
        ),
    ]
